# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: exit -1
  displayName: 'Run a one-line script'

- script: |
    sudo apt-get update
    sudo apt-get install libfftw3-dev
    git submodule update --init
    cd build
    mkdir linux
    cd linux
    cmake ../../generate -DCACTUS_TEST=ON -DCACTUS_MAIN=ON -DCMAKE_INSTALL_PREFIX=../../stage -DCMAKE_EXPORT_COMPILE_COMMANDS=YES
    cmake --build ./ --config Release
  displayName: 'Run a multi-line script'
